### ISSUE TITLE
Mi band 7 Supported? 

### ISSUE THREAD

**Issue by adeel23** [bigdigital/watchdrip#15]
Hi, I know the docs only support up to version 6 of the mi band.  Does anyone know if there's something in place to support version 7?

Thanks

**Comment by 4RK4N** [comment]
as far as i know xiaomi changed it so that only ONE app can connect to the watch. so it would be either xdrip data from watchdrip or everything else like notifications calendars workouts phone calls from the xiaomi app.
cant have both with their bew band so its not an option anymore really.

best suggestion would be to return the miband 7 and get an amazfit band 7. same form-factor with better compatibility
