### ISSUE TITLE
Missing graph

### ISSUE THREAD

**Issue by twinko** [bigdigital/watchdrip#5]
Already mentioned on Patreon. Im waiting for the graph to be implemented, This feature is depended on the following ZeppOS issue.
https://github.com/zepp-health/zeppos-forum/discussions/22

Just wrote it down to have it documented and for others to follow

**Comment by Nb-tst** [comment]
Sharing an idea, I don't know if useful. 
As long as there no way to have a graph, a raw one can be displayed given enough digits ( the more the better ).
Playing with the gadgetbridge weather idea I used digits as a graph. 
Indexing digits for a specific value  ( in my case given I used a weather value like humidity, but it should work with everything I guess ), like 4 to this:
![image](https://user-images.githubusercontent.com/82938674/212739260-c8b13543-907b-474b-804c-d74c482b8a98.png)

And 5 to this:
![image](https://user-images.githubusercontent.com/82938674/212739306-b9d72a35-bc4f-4be0-a80e-4ac78b31e55e.png)


Using a humidity value of 45 I got this ( every bg related value of this watchface is actually provided using weather info ):
![image](https://user-images.githubusercontent.com/82938674/212736276-12bff8fb-8a20-4b1e-b9b5-1d52f144256a.png)

Given that I have few digits to use, in fact 2 as the range is 0-255 and I have to use as much variability as I can, so the first  one which could be only 0-1-2 has to be excludes, I choose to represent only three possible values ( in range, high,low ) two times per digits, so to have a 3x3 config which would fill 9 numbers possibilities ( actually I can reduce to 7 because some combination are not useful ).
Having more digits to display a better translation could be useful, as every digit could have only one value to display and this could lead to a greater "resolution", say 0-9 to ( one low, 6 types of range, 3 types of high ).

**Comment by twinko** [comment]
@Nb-tst  
if u follow the link above to the teppOS git, u can see that the issue holding back the graph was solves by the zeppOS devs. Artem already saw it so i guess hes working on a solution :)
But maybe if he still encounters problems this could be a solution.

**Comment by 4RK4N** [comment]
first we would need that update on our watches. how long thats gonna take who knows. anything from days to months. i fear for the later...

**Comment by bigdigital** [comment]
I don't think you need to play with water data on Zepp OS for so simple graphs. It is possible to display a simple graph data even now. For example you can display it with image widgets. Draw dots by using a small dots images, and hi/low lines by using line images.

**Comment by 4RK4N** [comment]
> I don't think you need to play with water data on Zepp OS for so simple graphs. It is possible to display a simple graph data even now. For example you can display it with image widgets. Draw dots by using a small dots images, and hi/low lines by using line images.

i also thought about that already. have something like 36 dots images on the x-axis (12 per hour = 3 hours) and move them up or down to produce a graph. 
graph data is not yet transmitted to the watch, right? at least drawGraph() is empty in watchdrip.js and there is no model for graphData either.

**Comment by bigdigital** [comment]
the graph functionality on zepp os is already available so i'm closing this issue
